main: me.scalergames.SuperiorTags.Main
name: SuperiorTags
version: ALPHA-2
author: ScalerGames
description: A Minecraft tags plugin
api-version: 1.13
softdepend: [PlaceholderAPI, HeadDatabase]
commands:
  tags:
  test: