################################################################################################
#░██████╗██╗░░░██╗██████╗░███████╗██████╗░██╗░█████╗░██████╗░████████╗░█████╗░░██████╗░░██████╗#
#██╔════╝██║░░░██║██╔══██╗██╔════╝██╔══██╗██║██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔════╝░██╔════╝#
#╚█████╗░██║░░░██║██████╔╝█████╗░░██████╔╝██║██║░░██║██████╔╝░░░██║░░░███████║██║░░██╗░╚█████╗░#
#░╚═══██╗██║░░░██║██╔═══╝░██╔══╝░░██╔══██╗██║██║░░██║██╔══██╗░░░██║░░░██╔══██║██║░░╚██╗░╚═══██╗#
#██████╔╝╚██████╔╝██║░░░░░███████╗██║░░██║██║╚█████╔╝██║░░██║░░░██║░░░██║░░██║╚██████╔╝██████╔╝#
#╚═════╝░░╚═════╝░╚═╝░░░░░╚══════╝╚═╝░░╚═╝╚═╝░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚═╝░╚═════╝░╚═════╝░#
################################################################################################

#Prefix
Prefix: "&8&l[&3&lSuperiorTags&8&l] "

#Gui Settings
Title: "&3&lTags Menu"
Identifier: "&3Tag"
DefaultItem: "PAPER"