################################################################################################
#░██████╗██╗░░░██╗██████╗░███████╗██████╗░██╗░█████╗░██████╗░████████╗░█████╗░░██████╗░░██████╗#
#██╔════╝██║░░░██║██╔══██╗██╔════╝██╔══██╗██║██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔════╝░██╔════╝#
#╚█████╗░██║░░░██║██████╔╝█████╗░░██████╔╝██║██║░░██║██████╔╝░░░██║░░░███████║██║░░██╗░╚█████╗░#
#░╚═══██╗██║░░░██║██╔═══╝░██╔══╝░░██╔══██╗██║██║░░██║██╔══██╗░░░██║░░░██╔══██║██║░░╚██╗░╚═══██╗#
#██████╔╝╚██████╔╝██║░░░░░███████╗██║░░██║██║╚█████╔╝██║░░██║░░░██║░░░██║░░██║╚██████╔╝██████╔╝#
#╚═════╝░░╚═════╝░╚═╝░░░░░╚══════╝╚═╝░░╚═╝╚═╝░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚═╝░╚═════╝░╚═════╝░#
################################################################################################

#Prefix
Prefix: "&8&l[&3&lSuperiorTags&8&l] "

#Gui Settings
#Do not use color codes in the title setting it will break the plugin.
Title: "Tags Menu"
#Put your color codes for the tag menu here!
TitleColor: "&3&l"
Identifier: "Tag: "
IdentifierColor: "&3"
DefaultItem: "PAPER"